apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: infrastructure-exemplo-manual-prd
  namespace: default
  description: DNS Record claimed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"infrastructure-exemplo-manual-prd","system":"system:default/infrastructure","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"exemplo-manual","type":"A","originalType":"A","ttl":300,"values":["10.0.0.10"]}'
  labels:
    environment: prd
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:default/infrastructure
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "exemplo-manual"
  recordType: A
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 300
  values:
    - 10.0.0.10
