apiVersion: dns.infra.dock.tech/v1alpha1
kind: DNSRequest
metadata:
  name: req-example-alias-cloudfront
  namespace: dns-system
  labels:
    env: hml
    action: create_alias_record
    business-unit: banking
spec:
  requesterName: example.user@dock.tech
  action: create_alias_record
  env: hml
  hostedzone: myapp.hml.dock.tech
  businessUnit: banking
  originTicket: https://jira.dock.tech/browse/REQUEST-12345
  records:
    - name: cdn
      type: ALIAS
      aliasTarget:
        dnsName: d111.cloudfront.net
        resourceType: cloudfront
        evaluateTargetHealth: false
