apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-noTagsTest-hml-zone
  namespace: dns-eds437
  description: DNS Zone created by template
  annotations:
    dock.tech/created-at: '1787024237767'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-zone-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"hml","parentZone":{"id":"Z091442636MPUK86SZJ1T","name":"hml.arthurbryan.com","accountName":"hml-account"},"kind":"Zone","name":"dns-noTagsTest-hml-zone"}'
  labels:
    environment: hml
    cloud: aws
spec:
  type: DNSZone
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: hml
  name: dns-noTagsTest-hml-zone
  domain: cloud
  zoneName: noTagsTest.hml.arthurbryan.com
  delegatedFromZoneId: Z091442636MPUK86SZJ1T
  delegatedFromAccountName: hml-account
