apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-app-hml
  namespace: dns-eds437
  description: DNS Record claimed by template
  annotations:
    dock.tech/created-at: '1788367161379'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-app-hml","system":"system:dns-eds437/dns","environment":"hml","zone":{"id":"Z018927622SDKCSR4ZZ2F","name":"zoneclaimtest.hml.arthurbryan.com","accountName":"hml-account","environment":"hml"},"recordName":"app","type":"A","originalType":"A","entityRef":"resource:dns-eds437/dns-app-hml","ttl":300,"values":["203.0.113.20"]}'
  labels:
    environment: hml
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: hml
  name: dns-app-hml
  zoneId: Z018927622SDKCSR4ZZ2F
  zoneName: zoneclaimtest.hml.arthurbryan.com
  aws:
    account: "382598791794"
    accountName: hml-account
  recordName: "app"
  recordType: A
  import:
    existing: true
  ttl: 300
  values:
    - 203.0.113.20
