apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-test-hml
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-test-hml","system":"system:dns-eds437/dns","environment":"hml","zone":"hml.arthurbryan.com","zoneId":"Z091442636MPUK86SZJ1T","recordName":"test","type":"CNAME","originalType":"CNAME","values":["arthurbryan.com"],"enableWeightedRouting":false}'
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    environment: hml
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:dns-eds437/dns
  environment: hml
  zoneId: Z091442636MPUK86SZJ1T
  zoneName: hml.arthurbryan.com
  recordName: "test"
  recordType: CNAME
  aws:
    account: 382598791794
    accountName: hml-account
  ttl: 3600
  values:
    - arthurbryan.com
