apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-smoke-ns-hml
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-ns-hml","name":"dns-smoke-ns-hml","system":"system:dns-eds437/dns","environment":"hml","zone":"hml.arthurbryan.com","zoneId":"Z091442636MPUK86SZJ1T","recordName":"smoke-ns","type":"NS","enableWeightedRouting":false,"values":["ns3.example.com","ns4.example.com"],"ttl":172800}'
  labels:
    environment: hml
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:dns-eds437/dns
  environment: hml
  zoneId: Z091442636MPUK86SZJ1T
  zoneName: hml.arthurbryan.com
  recordName: "smoke-ns"
  recordType: NS
  aws:
    account: 382598791794
    accountName: hml-account
  ttl: 172800
  values:
    - ns3.example.com
    - ns4.example.com
