apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-rep-a-to-cname-hml
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-rep-a-to-cname-hml","system":"system:dns-eds437/dns","environment":"hml","zone":"hml.arthurbryan.com","zoneId":"Z091442636MPUK86SZJ1T","recordName":"rep-a-to-cname","type":"A","originalType":"A","values":["10.99.0.10"],"enableWeightedRouting":false}'
  labels:
    environment: hml
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:dns-eds437/dns
  environment: hml
  zoneId: Z091442636MPUK86SZJ1T
  zoneName: hml.arthurbryan.com
  recordName: rep-a-to-cname
  recordType: A
  aws:
    account: 382598791794
    accountName: hml-account
  ttl: 3600
  values:
    - 10.99.0.10
