---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arthur-bryan/aws-dns-crossplane-poc
    targetRevision: ape-platform-alignment
    path: lab/argocd/apps
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  ignoreDifferences:
    - group: argoproj.io
      kind: Application
      jqPathExpressions:
        - '.metadata.labels."argocd.argoproj.io/instance"'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
