configs:
  params:
    server.insecure: "true"

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    hostname: argocd.localtest.me
    annotations:
      nginx.ingress.kubernetes.io/ssl-passthrough: "false"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"

controller:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi

repoServer:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
