---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lab-provider-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/arthur-bryan/aws-dns-crossplane-poc
    targetRevision: ape-platform-alignment
    path: lab/provider-config
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 10
      backoff:
        duration: 10s
        maxDuration: 2m
        factor: 2
