---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: lab-dns-templates
  description: Lab-adapted DNS scaffolder templates (zone, zone-edit, record, record-edit)
spec:
  targets:
    - ./zone.yaml
    - ./zone-edit.yaml
    - ./record.yaml
    - ./record-edit.yaml
