apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dnszone-import
  labels:
    app.kubernetes.io/name: crossplane-compositions-dns
    composition.type: import
spec:
  compositeTypeRef:
    apiVersion: dock.tech/v1
    kind: DNSZone

  mode: Pipeline

  pipeline:
    - step: environmentConfigs
      functionRef:
        name: crossplane-contrib-function-environment-configs
      input:
        apiVersion: environmentconfigs.fn.crossplane.io/v1beta1
        kind: Input
        spec:
          environmentConfigs:
            - type: Selector
              selector:
                mode: Single
                matchLabels:
                  - type: FromCompositeFieldPath
                    key: environment
                    valueFromFieldPath: spec.environment

    - step: render-resources
      functionRef:
        name: crossplane-contrib-function-go-templating
      input:
        apiVersion: gotemplating.fn.crossplane.io/v1beta1
        kind: GoTemplate
        delims:
          left: '[['
          right: ']]'
        source: Inline
        inline:
          template: |
            [[- $params := .observed.composite.resource.spec ]]
            [[- $envs := index .context "apiextensions.crossplane.io/environment" ]]
            [[- $zoneName := $params.zoneName ]]
            [[- $accountName := default $params.aws.accountName $envs.aws.accountName ]]
            [[- $region := default $params.aws.region $envs.aws.region ]]
            [[- $domain := $params.domain ]]
            [[- $subdomain := $params.subdomain ]]
            [[- $system := $params.system ]]
            [[- $environment := $params.environment ]]
            [[- $comment := default "Managed by APE Platform" $params.comment ]]

            [[- $zoneId := "" ]]
            [[- range .observed.resources ]]
            [[- if eq .resource.kind "Zone" ]]
            [[- if .resource.status ]]
            [[- if .resource.status.atProvider ]]
            [[- if .resource.status.atProvider.zoneId ]]
            [[- $zoneId = .resource.status.atProvider.zoneId ]]
            [[- end ]]
            [[- end ]]
            [[- end ]]
            [[- end ]]
            [[- end ]]

            ---
            apiVersion: route53.aws.upbound.io/v1beta1
            kind: Zone
            metadata:
              name: [[ $zoneName | replace "." "-" ]]
              annotations:
                crossplane.io/external-name: [[ $zoneName ]]
                gotemplating.fn.crossplane.io/composition-resource-name: zone
            spec:
              providerConfigRef:
                name: [[ $accountName ]]
              managementPolicies:
                - Observe
                - Update
              deletionPolicy: Orphan
              forProvider:
                comment: [[ $comment ]]
                region: [[ $region ]]
                tags:
                  createdBy: ape-platform
                  domain: [[ $domain ]]
                  subdomain: [[ $subdomain ]]
                  system: [[ $system ]]
                  environment: [[ $environment ]]
                  [[- range $key, $value := $params.tags ]]
                  [[ $key ]]: [[ $value ]]
                  [[- end ]]

            [[- if and (gt (len $params.records) 0) $zoneId ]]
            [[- range $idx, $record := $params.records ]]
            ---
            apiVersion: route53.aws.upbound.io/v1beta1
            kind: Record
            metadata:
              name: [[ printf "%s-%s-%s" ($zoneName | replace "." "-") $record.name ($record.type | lower) ]]
              annotations:
                gotemplating.fn.crossplane.io/composition-resource-name: [[ printf "record-%d" $idx ]]
            spec:
              providerConfigRef:
                name: [[ $accountName ]]
              managementPolicies:
                - Observe
                - Update
              deletionPolicy: Orphan
              forProvider:
                name: [[ printf "%s.%s" $record.name $zoneName ]]
                type: [[ $record.type ]]
                zoneId: [[ $zoneId ]]
                region: [[ $region ]]
                [[- if $record.ttl ]]
                ttl: [[ $record.ttl ]]
                [[- end ]]
                [[- if $record.values ]]
                records: [[ $record.values | toJson ]]
                [[- end ]]
                [[- if $record.setIdentifier ]]
                setIdentifier: [[ $record.setIdentifier ]]
                [[- end ]]
                [[- if $record.weight ]]
                weight: [[ $record.weight ]]
                [[- end ]]
            [[- end ]]
            [[- end ]]

    - step: automatically-detect-ready-composed-resources
      functionRef:
        name: crossplane-contrib-function-auto-ready
