---
apiVersion: dock.tech/v1
kind: Zone
metadata:
  name: zone-internal.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"delegatedZone":"resource:system-infrastructure-prd/zone-arthurbryan.com","prefix":"internal","private":true,"vpcs":["resource:default/vpc-0410f81cfe1bba322"],"deletionProtection":false}'
spec:
  name: zone-internal.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneName: internal.arthurbryan.com
  delegatedFromZoneId: Z03010981ALJFZB4QLU8W
  visibility: private
  vpcs:
    - vpcId: vpc-0410f81cfe1bba322
      vpcRegion: us-east-1
  import:
    existing: true
    zoneId: Z023605847CN76CUAJYF
