---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-demo.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"name":"infrastructure-demo-prd","system":"system:default/infrastructure","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"demo","type":"CNAME","ttl":300,"values":["arthurbryan.com"],"enableWeightedRouting":false,"weight":100}'
spec:
  name: record-demo.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: demo
  type: CNAME
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 300
  values:
  - arthurbryan.com
