---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-new-test.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"name":"infrastructure-new-test-prd","system":"system:default/infrastructure","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"new-test","type":"CNAME","originalType":"CNAME","ttl":3600,"values":["arthurbryan.com"],"enableWeightedRouting":false}'
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  name: record-new-test.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: new-test
  type: CNAME
  aws:
    account: null
    accountName: null
  ttl: 3600
  values:
  - arthurbryan.com
