---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-weighted-weight-only-697842-wo.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-weighted-weight-only-697842","type":"A","routingPolicy":"weighted","setIdentifier":"wo","weight":100,"ttl":300,"values":["10.0.11.50"]}'
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  name: record-e2e-weighted-weight-only-697842-wo.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "e2e-weighted-weight-only-697842"
  type: A
  ttl: 300
  values:
    - 10.0.11.50
  setIdentifier: wo
  weight: 100
