---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-alias-alb-us-east-1-694854.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-alias-alb-us-east-1-694854","type":"ALIAS","routingPolicy":"simple","serviceType":"ALB","dnsName":"alb-create-1234567.us-east-1.elb.amazonaws.com","evaluateTargetHealth":true,"targetRegion":"us-east-1"}'
spec:
  name: record-e2e-alias-alb-us-east-1-694854.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-alias-alb-us-east-1-694854
  type: ALIAS
  aliasTarget:
    serviceType: ALB
    dnsName: alb-create-1234567.us-east-1.elb.amazonaws.com
    evaluateTargetHealth: true
    region: us-east-1
