---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-srv-694854.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-srv-694854","type":"SRV","ttl":600,"values":["10 60 5060 sip1.example.com","20 60 5060 sip2.example.com"],"routingPolicy":"simple"}'
spec:
  name: record-e2e-srv-694854.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "e2e-srv-694854"
  type: SRV
  ttl: 600
  values:
    - 10 60 5060 sip1.example.com
    - 20 60 5060 sip2.example.com
