---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-conc-rapid-024742.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-conc-rapid-024742","type":"A","ttl":300,"values":["10.0.40.30"],"routingPolicy":"simple"}'
spec:
  name: record-e2e-conc-rapid-024742.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "e2e-conc-rapid-024742"
  type: A
  ttl: 300
  values:
    - 10.0.40.30
