---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-ptr-694854.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-ptr-694854","type":"PTR","ttl":600,"values":["host2.example.com"],"routingPolicy":"simple"}'
spec:
  name: record-e2e-ptr-694854.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "e2e-ptr-694854"
  type: PTR
  ttl: 600
  values:
    - host2.example.com
