---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-conc-ttlrace-023923-primary.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-conc-ttlrace-023923","type":"A","ttl":900,"values":["10.0.42.10"],"routingPolicy":"weighted","setIdentifier":"primary","weight":50}'
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  name: record-e2e-conc-ttlrace-023923-primary.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "e2e-conc-ttlrace-023923"
  type: A
  ttl: 900
  values:
    - 10.0.42.10
  setIdentifier: primary
  weight: 50
