---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-api-2.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"api-2","type":"A","ttl":3600,"values":["10.0.0.20"],"routingPolicy":"simple"}'
spec:
  name: record-api-2.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: api-2
  type: A
  ttl: 3600
  values:
    - 10.0.0.20
  import:
    existing: true
