---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-alias-cloudfront-697842.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-alias-cloudfront-697842","type":"ALIAS","routingPolicy":"simple","serviceType":"CloudFront","dnsName":"d222-edit.cloudfront.net","evaluateTargetHealth":false}'
spec:
  name: record-e2e-alias-cloudfront-697842.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "e2e-alias-cloudfront-697842"
  type: ALIAS
  aliasTarget:
    serviceType: CloudFront
    dnsName: d222-edit.cloudfront.net
    evaluateTargetHealth: false
