---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-geoprox-694854-eu-west-1.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-geoprox-694854","type":"A","routingPolicy":"geoproximity","setIdentifier":"eu-west-1","geoproxAwsRegion":"eu-west-1","geoproxBias":0,"ttl":300,"values":["10.0.9.20"]}'
spec:
  name: record-e2e-geoprox-694854-eu-west-1.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-geoprox-694854
  type: A
  ttl: 300
  values:
    - 10.0.9.20
  setIdentifier: eu-west-1
  geoproximityRoutingPolicy:
    awsRegion: eu-west-1
