---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-cdn.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-cdn-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"cdn","type":"ALIAS","originalType":"ALIAS","serviceType":"Custom","dnsName":"d111111abcdef8.cloudfront.net","customZoneId":"Z2FDTNDATAQYW2","evaluateTargetHealth":false}'
spec:
  name: record-cdn.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: cdn
  type: ALIAS
  aws:
    account: 597230762851
    accountName: prd-account
  aliasTarget:
    serviceType: Custom
    dnsName: d111111abcdef8.cloudfront.net
    hostedZoneId: Z2FDTNDATAQYW2
    evaluateTargetHealth: false
