---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-smoke-ns.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-ns-prd","name":"dns-smoke-ns-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"smoke-ns","type":"NS","enableWeightedRouting":false,"values":["ns3.example.com","ns4.example.com"]}'
spec:
  name: record-smoke-ns.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: smoke-ns
  type: NS
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 172800
  values:
  - ns3.example.com
  - ns4.example.com
