---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-smoke-mx.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"name":"dns-smoke-mx-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"smoke-mx","type":"MX","originalType":"MX","ttl":3600,"values":["10
      mail.example.com"],"enableWeightedRouting":false}'
spec:
  name: record-smoke-mx.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: smoke-mx
  type: MX
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
  - 10 mail.example.com
