---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-prdttltest.arthurbryan.com-primary
  namespace: system-dns-prd
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"prd","zone":{"id":"Z03010981ALJFZB4QLU8W","name":"arthurbryan.com","accountName":"prd-account","environment":"prd"},"kind":"Record","name":"dns-prdttltest-prd-primary","type":"A","enableWeightedRouting":true,"values":["10.50.50.1"],"setIdentifier":"primary","weight":100,"recordName":"prdttltest","entityRef":"resource:dns-eds437/dns-prdttltest-prd-primary"}'
spec:
  name: record-prdttltest.arthurbryan.com-primary
  domain: cross
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: prdttltest
  recordType: A
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
  - 10.50.50.1
  setIdentifier: primary
  weight: 255
