---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-smoke-aaaa.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-aaaa-prd","name":"dns-smoke-aaaa-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"smoke-aaaa","type":"AAAA","enableWeightedRouting":false,"values":["2001:db8::200"],"ttl":3600}'
spec:
  name: record-smoke-aaaa.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: smoke-aaaa
  type: AAAA
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
  - 2001:db8::200
