---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-smoke-txt.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-txt-prd","name":"dns-smoke-txt-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"smoke-txt","type":"TXT","enableWeightedRouting":false,"values":["platform=edited"],"ttl":3600}'
spec:
  name: record-smoke-txt.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: smoke-txt
  type: TXT
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
  - platform=edited
