---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-smoke-srv.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-srv-prd","name":"dns-smoke-srv-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"smoke-srv","type":"SRV","enableWeightedRouting":false,"values":["20
      50 5061 sip2.example.com"],"ttl":3600}'
spec:
  name: record-smoke-srv.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: smoke-srv
  type: SRV
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
  - 20 50 5061 sip2.example.com
