---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-rep-a-to-cname.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-rep-a-to-cname-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"rep-a-to-cname","type":"A","originalType":"A","values":["10.99.0.10"],"enableWeightedRouting":false}'
spec:
  name: record-rep-a-to-cname.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: rep-a-to-cname
  type: A
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
  - 10.99.0.10
