---
apiVersion: dock.tech/v1
kind: DNSZone
metadata:
  name: zone-arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"kind":"Zone","parentZone":{"id":"Z03010981ALJFZB4QLU8W","name":"arthurbryan.com","accountName":"prd"},"environment":"dev","name":"dns-dev-dev-zone"}'
spec:
  name: zone-arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: dev
  zoneName: arthurbryan.com
  aws:
    account: null
    accountName: null
  delegatedFromZoneId: Z03010981ALJFZB4QLU8W
  delegatedFromAccountName: prd
