apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-www-dev
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-www-dev","name":"dns-www-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"www","type":"CNAME","values":["api.dev.arthurbryan.com"],"enableWeightedRouting":false,"originalType":"CNAME"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-www-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "www"
  recordType: CNAME
  ttl: 3600
  values:
    - api.dev.arthurbryan.com
