apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-claimapprunner-dev
  namespace: dns-eds437
  description: DNS Record claimed by template
  annotations:
    dock.tech/created-at: '1787159448275'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-claimapprunner-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"claimapprunner","type":"ALIAS","originalType":"ALIAS","entityRef":"resource:dns-eds437/dns-claimapprunner-dev","serviceType":"AppRunner","dnsName":"abc123def456.us-east-1.awsapprunner.com","evaluateTargetHealth":false,"region":"us-east-1"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-claimapprunner-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "claimapprunner"
  recordType: ALIAS
  import:
    existing: true
  aliasTarget:
    serviceType: AppRunner
    dnsName: abc123def456.us-east-1.awsapprunner.com
    evaluateTargetHealth: false
    region: us-east-1
