apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-editclaimweighted-dev-primary
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787030538877'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-editclaimweighted-dev-primary","name":"dns-editclaimweighted-dev-primary","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"editclaimweighted","type":"A","values":["10.0.6.2"],"enableWeightedRouting":true,"setIdentifier":"primary","weight":80,"originalType":"A"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-editclaimweighted-dev-primary
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "editclaimweighted"
  recordType: A
  ttl: 600
  values:
    - 10.0.6.2
  setIdentifier: primary
  weight: 80
