apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-evelasticbeanstalk-dev
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787161163803'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-evelasticbeanstalk-dev","type":"ALIAS","enableWeightedRouting":false,"serviceType":"AppRunner","region":"us-east-1","dnsName":"ev-eb-to-apprunner.us-east-1.awsapprunner.com","evaluateTargetHealth":false,"values":[null],"recordName":"evelasticbeanstalk","entityRef":"resource:dns-eds437/dns-evelasticbeanstalk-dev","originalType":"ALIAS"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-evelasticbeanstalk-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "evelasticbeanstalk"
  recordType: ALIAS
  aliasTarget:
    serviceType: AppRunner
    dnsName: ev-eb-to-apprunner.us-east-1.awsapprunner.com
    region: us-east-1
    evaluateTargetHealth: false
