apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-evweightedtest-dev-primary
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787161377123'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-evweightedtest-dev-primary","type":"A","enableWeightedRouting":true,"values":["10.95.95.1"],"setIdentifier":"primary","weight":33,"recordName":"evweightedtest","entityRef":"resource:dns-eds437/dns-evweightedtest-dev-primary","originalType":"A"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-evweightedtest-dev-primary
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "evweightedtest"
  recordType: A
  ttl: 600
  values:
    - 10.95.95.1
  setIdentifier: primary
  weight: 84
