apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ steps.computeRecordNames.output.result[each.key].entityName }}
  namespace: ${{ steps.fetchSystem.output.entity.metadata.namespace }}
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: ${{ "'" + now() + "'" }}
    dock.tech/created-by: ${{ user.ref }}
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: ${{ "'" + steps.computeRecordNames.output.result[each.key].params | dump + "'" }}
  labels:
    environment: ${{ parameters.environment }}
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: ${{ steps.fetchSystem.output.entity.spec.owner }}
  tribe: ${{ steps.fetchSystem.output.entity.spec.tribe }}
  system: ${{ parameters.system }}
  environment: ${{ parameters.environment }}
  name: ${{ steps.computeRecordNames.output.result[each.key].entityName }}
  zoneId: ${{ parameters.zone.id }}
  zoneName: ${{ parameters.zone.name }}
  recordName: ${{ steps.computeRecordNames.output.result[each.key].recordName }}
  recordType: ${{ each.value.type }}
  {%- if each.value.type != 'ALIAS' %}
  ttl: ${{ steps.computeRecordNames.output.result[each.key].ttl }}
  values:
  {%- for value in each.value.values %}
    - ${{ value }}
  {%- endfor %}
  {%- else %}
  aliasTarget:
    serviceType: ${{ each.value.serviceType }}
    dnsName: ${{ each.value.dnsName }}
    {%- if each.value.serviceType == 'Custom' %}
    hostedZoneId: ${{ each.value.customZoneId }}
    {%- endif %}
    evaluateTargetHealth: ${{ each.value.evaluateTargetHealth }}
  {%- endif %}
  {%- if each.value.enableWeightedRouting %}
  setIdentifier: ${{ each.value.setIdentifier }}
  weight: ${{ each.value.weight }}
  {%- endif %}
