apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-scn-alias-cf-dev
  namespace: dns-eds437
  description: DNS Record claimed by template
  annotations:
    dock.tech/created-at: '1787028003098'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-scn-alias-cf-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"scn-alias-cf","type":"ALIAS","originalType":"ALIAS","entityRef":"resource:dns-eds437/dns-scn-alias-cf-dev","serviceType":"CloudFront","dnsName":"d111111abcdef8.cloudfront.net","evaluateTargetHealth":false}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-scn-alias-cf-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "scn-alias-cf"
  recordType: ALIAS
  import:
    existing: true
  aliasTarget:
    serviceType: Custom
    dnsName: d111111abcdef8.cloudfront.net
    hostedZoneId: Z2FDTNDATAQYW2
    evaluateTargetHealth: false
