apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-editnewWEIGHTED-dev-primary
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787030334027'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-editnewWEIGHTED-dev-primary","type":"A","values":["10.0.5.2"],"enableWeightedRouting":true,"setIdentifier":"primary","weight":100,"recordName":"editnewWEIGHTED","entityRef":"resource:/dns-editnewWEIGHTED-dev-primary"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-editnewWEIGHTED-dev-primary
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: editnewWEIGHTED
  recordType: A
  ttl: 600
  values:
    - 10.0.5.2
  setIdentifier: primary
  weight: 100
