apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-e2ecname017550-dev
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-e2ecname017550-dev","type":"CNAME","values":["target.example.com"],"enableWeightedRouting":false,"recordName":"e2ecname017550","entityRef":"resource:/dns-e2ecname017550-dev"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-e2ecname017550-dev
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2ecname017550
  recordType: CNAME
  ttl: 3600
  values:
    - target.example.com
