apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-scn-mx-dev
  namespace: dns-eds437
  description: DNS Record claimed by template
  annotations:
    dock.tech/created-at: '1787028021673'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-scn-mx-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"scn-mx","type":"MX","originalType":"MX","entityRef":"resource:dns-eds437/dns-scn-mx-dev","ttl":300,"values":["10 mail.example.com"]}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-scn-mx-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "scn-mx"
  recordType: MX
  import:
    existing: true
  ttl: 300
  values:
    - 10 mail.example.com
