apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-editnewCNAME-dev
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787030334005'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-editnewCNAME-dev","type":"CNAME","values":["target1.example.com"],"enableWeightedRouting":false,"recordName":"editnewCNAME","entityRef":"resource:/dns-editnewCNAME-dev"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-editnewCNAME-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: editnewCNAME
  recordType: CNAME
  ttl: 3600
  values:
    - target1.example.com
