apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-claim-cname-dev
  namespace: dns-eds437
  description: DNS Record claimed by template
  annotations:
    dock.tech/created-at: '1787027541915'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-claim-cname-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"claim-cname","type":"CNAME","originalType":"CNAME","entityRef":"resource:dns-eds437/dns-claim-cname-dev","ttl":300,"values":["target.example.com"]}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-claim-cname-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "claim-cname"
  recordType: CNAME
  import:
    existing: true
  ttl: 300
  values:
    - target.example.com
