apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-smoke-mx-dev
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-mx-dev","name":"dns-smoke-mx-dev","system":"system:dns-eds437/dns","environment":"dev","zone":"dev.arthurbryan.com","zoneId":"Z0945364EYNE5KZW0WIF","recordName":"smoke-mx","type":"MX","enableWeightedRouting":false,"values":["20 mail2.example.com"],"ttl":3600}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:dns-eds437/dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: "smoke-mx"
  recordType: MX
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
    - 20 mail2.example.com
