apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-evweight-dev-primary
  namespace: dns-eds437
  description: DNS Record claimed by template
  annotations:
    dock.tech/created-at: '1787161058024'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-evweight-dev-primary","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"evweight","type":"A","originalType":"A","entityRef":"resource:dns-eds437/dns-evweight-dev-primary","enableWeightedRouting":true,"setIdentifier":"primary","weight":50,"ttl":600,"values":["10.90.90.1"]}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-evweight-dev-primary
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "evweight"
  recordType: A
  import:
    existing: true
  setIdentifier: primary
  weight: 128
  ttl: 600
  values:
    - 10.90.90.1
