apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-replace-a-to-cname-dev
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-replace-a-to-cname-dev","name":"dns-replace-a-to-cname-dev","system":"system:dns-eds437/dns","environment":"dev","zone":"dev.arthurbryan.com","zoneId":"Z0945364EYNE5KZW0WIF","recordName":"replace-a-to-cname","enableWeightedRouting":false,"type":"CNAME","values":["cname-target.example.com"]}'
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    environment: dev
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:dns-eds437/dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: "replace-a-to-cname"
  recordType: CNAME
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
    - cname-target.example.com
