apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-testweighted-dev-primary
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787181964665'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-testweighted-dev-primary","type":"A","enableWeightedRouting":true,"values":["10.70.70.10"],"setIdentifier":"primary","weight":70,"recordName":"testweighted","entityRef":"resource:dns-eds437/dns-testweighted-dev-primary"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-testweighted-dev-primary
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: testweighted
  recordType: A
  ttl: 600
  values:
    - 10.70.70.10
  setIdentifier: primary
  weight: 178
