apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-dev-arthurbryan-com-dev-zone
  namespace: dns-eds437
  description: DNS Zone created by template
  annotations:
    dock.tech/created-at: '1789761239110'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-zone-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","kind":"Zone","private":false}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSZone
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-dev-arthurbryan-com-dev-zone
  zoneName: dns.dev.arthurbryan.com
  visibility: public
  aws:
    account: "309670275661"
    accountName: dev-account
  delegatedFromZoneId: Z0945364EYNE5KZW0WIF
  delegatedFromAccountName: dnszone-dev
