apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-albtest2-dev
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787064726462'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-albtest2-dev","name":"dns-albtest2-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"albtest2","type":"ALIAS","enableWeightedRouting":false,"serviceType":"CloudFront","dnsName":"d111111abcdef8.cloudfront.net","evaluateTargetHealth":false,"region":"global","originalType":"ALIAS"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-albtest2-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "albtest2"
  recordType: ALIAS
  aliasTarget:
    serviceType: CloudFront
    dnsName: d111111abcdef8.cloudfront.net
    evaluateTargetHealth: false
