apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-ebtest-dev
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787144215470'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-ebtest-dev","type":"ALIAS","enableWeightedRouting":false,"serviceType":"ElasticBeanstalk","region":"us-east-1","dnsName":"my-eb-env.us-east-1.elasticbeanstalk.com","evaluateTargetHealth":false,"values":[null],"recordName":"ebtest","entityRef":"resource:dns-eds437/dns-ebtest-dev"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-ebtest-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: ebtest
  recordType: ALIAS
  aliasTarget:
    serviceType: ElasticBeanstalk
    dnsName: my-eb-env.us-east-1.elasticbeanstalk.com
    region: us-east-1
    evaluateTargetHealth: false
