apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-retestupdate-dev
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787031547461'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-retestupdate-dev","name":"dns-retestupdate-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"retestupdate","type":"A","values":["10.0.8.1","10.0.8.2"],"enableWeightedRouting":false,"originalType":"A"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-retestupdate-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "retestupdate"
  recordType: A
  ttl: 3600
  values:
    - 10.0.8.1
    - 10.0.8.2
  import:
    existing: true
