apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-weightzero-dev-only
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787150554559'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-weightzero-dev-only","type":"A","enableWeightedRouting":true,"values":["10.30.30.1"],"setIdentifier":"only","weight":0,"recordName":"weightzero","entityRef":"resource:dns-eds437/dns-weightzero-dev-only"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-weightzero-dev-only
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: weightzero
  recordType: A
  ttl: 600
  values:
    - 10.30.30.1
  setIdentifier: only
  weight: 0
