apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-albfinal-dev
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787066305428'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-albfinal-dev","name":"dns-albfinal-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"albfinal","type":"ALIAS","enableWeightedRouting":false,"serviceType":"ALB","region":"us-east-1","dnsName":"my-alb-final-test.us-west-2.elb.amazonaws.com","evaluateTargetHealth":false,"originalType":"ALIAS"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-albfinal-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "albfinal"
  recordType: ALIAS
  aliasTarget:
    serviceType: ALB
    dnsName: my-alb-final-test.us-west-2.elb.amazonaws.com
    region: us-east-1
    evaluateTargetHealth: false
