apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-scn-weighted2-dev
  namespace: dns-eds437
  description: DNS Record claimed by template
  annotations:
    dock.tech/created-at: '1787028026904'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"name":"dns-scn-weighted2-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"scn-weighted2","type":"A","originalType":"A","entityRef":"resource:dns-eds437/dns-scn-weighted2-dev","enableWeightedRouting":true,"setIdentifier":"east","weight":50,"ttl":300,"values":["10.0.3.10"]}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: dns-scn-weighted2-dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "scn-weighted2"
  recordType: A
  import:
    existing: true
  setIdentifier: east
  weight: 50
  ttl: 300
  values:
    - 10.0.3.10
