apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: ${{ parameters.name }}
  namespace: ${{ steps.fetchSystem.output.entity.metadata.namespace }}
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: ${{ "'" + now() + "'" }}
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '${{ steps.buildEditParams.output.result | dump }}'
  labels:
    environment: ${{ parameters.environment }}
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: ${{ steps.fetchSystem.output.entity.spec.owner }}
  system: ${{ parameters.system }}
  environment: ${{ parameters.environment }}
  zoneId: ${{ parameters.zone.id }}
  zoneName: ${{ parameters.zone.name }}
  recordName: ${{ steps.extractRecordName.output.result }}
  recordType: ${{ parameters.type }}
  aws:
    account: ${{ steps.deriveAccount.output.result.accountId }}
    accountName: ${{ steps.deriveAccount.output.result.accountName }}
  {%- if parameters.type != 'ALIAS' %}
  ttl: ${{ steps.deriveTtl.output.result }}
  values:
  {%- for value in parameters.values %}
    - ${{ value }}
  {%- endfor %}
  {%- else %}
  aliasTarget:
    serviceType: ${{ parameters.serviceType }}
    dnsName: ${{ parameters.dnsName }}
    {%- if parameters.serviceType == 'Custom' %}
    hostedZoneId: ${{ parameters.customZoneId }}
    {%- endif %}
    evaluateTargetHealth: ${{ parameters.evaluateTargetHealth }}
  {%- endif %}
  {%- if parameters.enableWeightedRouting %}
  setIdentifier: ${{ parameters.setIdentifier }}
  weight: ${{ parameters.weight }}
  {%- endif %}
