apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: matrixtxt3
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787598574545'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"matrixtxt3","type":"TXT","values":["v=spf1 include:_spf.google.com ~all","google-site-verification=abc123"],"recordName":"matrixtxt3","entityRef":"resource:dns-eds437/matrixtxt3"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: matrixtxt3
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: matrixtxt3
  recordType: TXT
  ttl: 3600
  values:
    - v=spf1 include:_spf.google.com ~all
    - google-site-verification=abc123
