apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: matrixa2
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787598574521'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"matrixa2","entityRef":"resource:dns-eds437/matrixa2","type":"A","recordName":"matrixa2","values":["10.20.1.2","10.20.1.3"],"originalType":"A"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: matrixa2
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "matrixa2"
  recordType: A
  ttl: 3600
  values:
    - 10.20.1.2
    - 10.20.1.3
