apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: matrixaaaa3
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787598574532'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"matrixaaaa3","type":"AAAA","values":["fe80::1"],"recordName":"matrixaaaa3","entityRef":"resource:dns-eds437/matrixaaaa3"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: matrixaaaa3
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: matrixaaaa3
  recordType: AAAA
  ttl: 3600
  values:
    - fe80::1
