apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: mix6-aaaa
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787606592193'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"mix6-aaaa","type":"AAAA","values":["2001:db8::6"],"recordName":"mix6-aaaa","entityRef":"resource:dns-eds437/mix6-aaaa"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: mix6-aaaa
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: mix6-aaaa
  recordType: AAAA
  ttl: 3600
  values:
    - 2001:db8::6
