apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: roundtest-primary
  namespace: dns-eds437
  description: DNS Record created by template
  annotations:
    dock.tech/created-at: '1787190834040'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"roundtest-primary","type":"A","values":["10.0.0.1"],"enableWeightedRouting":true,"setIdentifier":"primary","weight":70,"recordName":"roundtest","entityRef":"resource:dns-eds437/roundtest-primary"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: roundtest-primary
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: roundtest
  recordType: A
  ttl: 600
  values:
    - 10.0.0.1
  setIdentifier: primary
  weight: 178
