apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: valueedittest
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/created-at: '1787336209929'
    dock.tech/created-by: user:development/guest
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"valueedittest","entityRef":"resource:dns-eds437/valueedittest","recordName":"valueedittest","type":"ALIAS","serviceType":"CloudFront","dnsName":"d444444abcdefb.cloudfront.net","originalType":"ALIAS"}'
  labels:
    environment: dev
    cloud: aws
spec:
  type: DNSRecord
  cloud: aws
  owner: group:default/infrastructure
  tribe: 
  system: system:dns-eds437/dns
  environment: dev
  name: valueedittest
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  aws:
    account: "309670275661"
    accountName: dev-account
  recordName: "valueedittest"
  recordType: ALIAS
  aliasTarget:
    serviceType: CloudFront
    dnsName: d444444abcdefb.cloudfront.net
