apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-rep-a-to-cname-prd
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-rep-a-to-cname-prd","name":"dns-rep-a-to-cname-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"rep-a-to-cname","enableWeightedRouting":false,"type":"CNAME","values":["cname-target.example.com"]}'
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    environment: prd
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:dns-eds437/dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "rep-a-to-cname"
  recordType: CNAME
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
    - cname-target.example.com
