apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: dns-smoke-aaaa-prd
  namespace: dns-eds437
  description: DNS Record managed by template
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-aaaa-prd","name":"dns-smoke-aaaa-prd","system":"system:dns-eds437/dns","environment":"prd","zone":"arthurbryan.com","zoneId":"Z03010981ALJFZB4QLU8W","recordName":"smoke-aaaa","type":"AAAA","enableWeightedRouting":false,"values":["2001:db8::200"]}'
  labels:
    environment: prd
    cloud: aws
spec:
  type: dns-record
  cloud: aws
  owner: group:default/infrastructure
  system: system:dns-eds437/dns
  environment: prd
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: "smoke-aaaa"
  recordType: AAAA
  aws:
    account: 597230762851
    accountName: prd-account
  ttl: 3600
  values:
    - 2001:db8::200
