apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: poc-dns-entities
  description: Root location for all PoC DNS entities and templates
spec:
  targets:
    # DNS system, domains, groups (System entity "dns" is defined here already)
    - ./catalog-info.yaml
    # DNS zone/record resources per environment
    - ./dock-tech/systems/dns-eds437/resources/dev
    - ./dock-tech/systems/dns-eds437/resources/hml
    - ./dock-tech/systems/dns-eds437/resources/prd
    # Crossplane claim files (environments/)
    - ./environments/cross/cloud/dns/dev/resources/aws/dev.arthurbryan.com
    - ./environments/cross/cloud/dns/hml/resources/aws/hml.arthurbryan.com
    - ./environments/cross/cloud/dns/prd/resources/aws/arthurbryan.com
    - ./environments/cross/cloud/dns/prd/resources/aws/dev.arthurbryan.com
    - ./environments/cross/cloud/dns/prd/resources/aws/hml.arthurbryan.com
    # Namespace definitions
    - ./namespaces/dns-eds437.yaml
    - ./namespaces/system-infrastructure-dev.yaml
    - ./namespaces/system-infrastructure-hml.yaml
    - ./namespaces/system-infrastructure-prd.yaml
