---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-checkout-134856.hml.arthurbryan.com
  namespace: system-infrastructure-hml
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-hml/zone-hml.arthurbryan.com","recordName":"checkout-134856","type":"A","ttl":3600,"values":["10.0.0.20"],"routingPolicy":"simple"}'
spec:
  name: record-checkout-134856.hml.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: hml
  aws:
    account: 382598791794
    accountName: hml-account
  zoneId: Z02234832G6QGRGKEEUMU
  zoneName: hml.arthurbryan.com
  recordName: "checkout-134856"
  type: A
  ttl: 3600
  values:
    - 10.0.0.20
