---
apiVersion: dock.tech/v1
kind: Zone
metadata:
  name: zone-hml.arthurbryan.com
  namespace: system-infrastructure-hml
  annotations:
    dock.tech/scaffolder-parameters: '{"environment":"hml","private":false,"delegatedZone":"resource:system-infrastructure-prd/zone-arthurbryan.com","prefix":"hml"}'
spec:
  name: zone-hml.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: hml
  aws:
    account: 382598791794
    accountName: hml-account
  zoneName: hml.arthurbryan.com
  delegatedFromZoneId: Z03010981ALJFZB4QLU8W
  delegatedFromAccountName: prd-account
  visibility: public
