---
apiVersion: dock.tech/v1
kind: Zone
metadata:
  name: zone-test.arthurbryan.com
  namespace: system-infrastructure-prd
  annotations:
    dock.tech/scaffolder-parameters: '{"environment":"prd","private":false,"delegatedZone":"resource:system-infrastructure-prd/zone-arthurbryan.com","prefix":"test"}'
spec:
  name: zone-test.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: prd
  aws:
    account: 597230762851
    accountName: prd-account
  zoneName: test.arthurbryan.com
  delegatedFromZoneId: Z03010981ALJFZB4QLU8W
  delegatedFromAccountName: prd-account
  visibility: public
