---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: vpc-0dd3eaef2e5c11f69
  title: vpc-0dd3eaef2e5c11f69 (us-east-1, dev-account)
  description: "VPC vpc-0dd3eaef2e5c11f69 in us-east-1 (dev-account), CIDR 172.31.0.0/16, default"
  annotations:
    dock.tech/vpc-id: vpc-0dd3eaef2e5c11f69
    dock.tech/vpc-region: us-east-1
    dock.tech/vpc-cidr: 172.31.0.0/16
    dock.tech/vpc-is-default: "true"
    dock.tech/aws-account-id: "309670275661"
    dock.tech/aws-account-name: dev-account
  tags:
    - aws
    - vpc
    - us-east-1
    - dev-account
    - default
spec:
  type: aws-vpc-default
  owner: group:default/infrastructure
