---
apiVersion: dock.tech/v1
kind: DNSZone
metadata:
  name: zone-hml.arthurbryan.com
  namespace: system-dns-prd
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"kind":"Zone","parentZone":{"id":"Z03010981ALJFZB4QLU8W","name":"arthurbryan.com","accountName":"prd-account"},"environment":"hml","name":"dns-hml-hml-zone"}'
spec:
  name: zone-hml.arthurbryan.com
  domain: cross
  system: dns
  environment: hml
  zoneName: hml.arthurbryan.com
  aws:
    account: 382598791794
    accountName: hml-account
  delegatedFromZoneId: Z03010981ALJFZB4QLU8W
  delegatedFromAccountName: dnszone-prd
  import:
    existing: true
    zoneId: Z091442636MPUK86SZJ1T
