---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-geoprox-gp1-eu-west-1.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-dev/zone-arthurbryan.com","recordName":"e2e-geoprox-gp1","type":"A","routingPolicy":"geoproximity","setIdentifier":"eu-west-1","geoproxAwsRegion":"eu-west-1","geoproxBias":0,"ttl":600,"values":["10.0.9.21"]}'
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  name: record-e2e-geoprox-gp1-eu-west-1.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 597230762851
    accountName: dev-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-geoprox-gp1
  type: A
  ttl: 600
  values:
    - 10.0.9.21
  setIdentifier: eu-west-1
  geoproximityRoutingPolicy:
    awsRegion: eu-west-1
