---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-ns-n2.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-dev/zone-arthurbryan.com","recordName":"e2e-ns-n2","type":"NS","ttl":86400,"values":["ns1.example.com","ns2.example.com","ns3.example.com"],"routingPolicy":"simple"}'
spec:
  name: record-e2e-ns-n2.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 597230762851
    accountName: dev-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-ns-n2
  type: NS
  ttl: 86400
  values:
    - ns1.example.com
    - ns2.example.com
    - ns3.example.com
