---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-cname-c1.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-dev/zone-arthurbryan.com","recordName":"e2e-cname-c1","type":"CNAME","ttl":600,"values":["e2e-target-2.example.com"],"routingPolicy":"simple"}'
spec:
  name: record-e2e-cname-c1.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 597230762851
    accountName: dev-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-cname-c1
  type: CNAME
  ttl: 600
  values:
    - e2e-target-2.example.com
