---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-multi-mv1-host-2.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-dev/zone-arthurbryan.com","recordName":"e2e-multi-mv1","type":"A","routingPolicy":"multivalue","setIdentifier":"host-2","ttl":300,"values":["10.0.10.20"]}'
spec:
  name: record-e2e-multi-mv1-host-2.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 597230762851
    accountName: dev-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-multi-mv1
  type: A
  ttl: 300
  values:
    - 10.0.10.20
  setIdentifier: host-2
  multivalueAnswerRoutingPolicy: true
