---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-e2e-alias-custom-l1.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-dev/zone-arthurbryan.com","recordName":"e2e-alias-custom-l1","type":"ALIAS","routingPolicy":"simple","serviceType":"Custom","dnsName":"d222-edit.cloudfront.net","evaluateTargetHealth":false,"customZoneId":"Z2FDTNDATAQYW2"}'
spec:
  name: record-e2e-alias-custom-l1.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 597230762851
    accountName: dev-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-alias-custom-l1
  type: ALIAS
  aliasTarget:
    serviceType: Custom
    dnsName: d222-edit.cloudfront.net
    evaluateTargetHealth: false
    hostedZoneId: Z2FDTNDATAQYW2
