---
apiVersion: dock.tech/v1
kind: Zone
metadata:
  name: zone-internal.dev.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"delegatedZone":"resource:system-infrastructure-dev/zone-dev.arthurbryan.com","prefix":"internal","environment":"dev","private":true,"vpcs":["resource:default/vpc-0be51ad70cd373b81"]}'
spec:
  name: zone-internal.dev.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 309670275661
    accountName: dev-account
  zoneName: internal.dev.arthurbryan.com
  delegatedFromZoneId: Z08530593BJKRSAKMDBYE
  delegatedFromAccountName: dev-account
  visibility: private
  vpcs:
    - vpcId: vpc-0dd3eaef2e5c11f69
      vpcRegion: us-east-1
      accountName: dev-account
    - vpcId: vpc-0be51ad70cd373b81
      vpcRegion: us-east-1
      accountName: dev-account
