---
apiVersion: v1
kind: Namespace
metadata:
  name: system-dns-prd
  labels:
    ape.dock.tech/domain: cloud
    ape.dock.tech/subdomain: cloud
    ape.dock.tech/system: dns
    ape.dock.tech/environment: prd
