apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: claimtest
  namespace: system-infrastructure-prd
  description: AWS Route53 DNS Record (claimed)
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"recordName":"claimtest","type":"A","ttl":600,"values":["203.0.113.77"]}'
    dock.tech/import-existing: "true"
  labels:
    environment: prd
    cloud: aws
spec:
  type: Record
  cloud: aws
  owner: group:default/infrastructure
  system: infrastructure
  environment: prd
  domain: cross
  subdomain: cloud
  aws:
    account: "597230762851"
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: claimtest.arthurbryan.com
  recordType: A
  ttl: 600
  values:
    - 203.0.113.77
