apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: e2e-claim
  namespace: system-infrastructure-prd
  description: DNS Record (claimed; edited)
  annotations:
    dock.tech/scaffolder-editable-template: dns-record-edit
    dock.tech/scaffolder-parameters: '{"recordName":"e2e-claim","type":"CNAME","ttl":600,"values":["arthurbryan.com"]}'
    dock.tech/import-existing: "true"
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    environment: prd
    cloud: aws
spec:
  type: Record
  cloud: aws
  owner: group:default/infrastructure
  system: infrastructure
  environment: prd
  domain: cross
  subdomain: cloud
  aws:
    account: "597230762851"
    accountName: prd-account
  zoneId: Z03010981ALJFZB4QLU8W
  zoneName: arthurbryan.com
  recordName: e2e-claim
  recordType: CNAME
  ttl: 600
  values:
    - arthurbryan.com
