apiVersion: dns.crossplane.poc/v1alpha1
kind: DNSZone
metadata:
  name: infraprd-hml-dock-tech
  namespace: dns-system
  annotations:
    crossplane.io/external-name: "Z0195231ON0MEFO4W8P4"
spec:
  zoneName: infraprd.hml.dock.tech
  environment: prd
  compositionRef:
    name: dnszones.aws.dns.crossplane.poc.observe
  tags:
    Account: prd
    Environment: prd
    ManagedBy: crossplane
    Team: infrastructure-services
    Tribe: cloud
  comment: Production environment zone (observe-only)
  records:
    - name: "_df4b01a1202706a789eecc3dcecc221d"
      type: CNAME
      ttl: 3600
      values:
        - "_f6302af320a6d37b74b2d47c3678826e.kkddzztszm.acm-validations.aws"
    - name: "_df4b01a1202706a789eecc3dcecc331f"
      type: CNAME
      ttl: 3600
      values:
        - "_f6302af320a6d37b74b2d47c3678826e.kkddzztszm.acm-validations.aws"
    - name: "aaa-0006"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaa-0007"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaa-0008"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaa-0009"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaa-0010"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaa-0011"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaa-0015"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaa-00015"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaa-00016"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaa-00017"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaa-0005"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaa-0012"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaa-0013"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaaa-00017"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaaa-00018"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaaa-00019"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "aaaaa-00020"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "adsdasdasdasdasdaw3e4ase"
      type: CNAME
      ttl: 3600
      values:
        - "asdadasd.dock.tech"
    - name: "api-prd-1762820287"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1762826936"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1762829955"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1762887916"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1762891698"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1764636698"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1764638847"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1764678103"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "api-prd-1764679445"
      type: A
      ttl: 300
      values:
        - "203.0.113.50"
    - name: "asdadasdasd"
      type: A
      aliasTarget:
        dnsName: "asdasdasd.cloudfront.net"
        hostedZoneId: "Z2FDTNDATAQYW2"
        evaluateTargetHealth: false
    - name: "asdasdasdasd"
      type: A
      ttl: 3600
      values:
        - "201.206.81.14"
    - name: "asfasd4as3easd"
      type: A
      aliasTarget:
        dnsName: "asedacc.cloudfront.net"
        hostedZoneId: "Z2FDTNDATAQYW2"
        evaluateTargetHealth: false
    - name: "asfnasfhga78sf"
      type: A
      aliasTarget:
        dnsName: "a12348q7w5ar68.cloudfront.net"
        hostedZoneId: "Z2FDTNDATAQYW2"
        evaluateTargetHealth: false
    - name: "askojifcayus7dfasrf"
      type: A
      aliasTarget:
        dnsName: "asiduausf.cloudfront.net"
        hostedZoneId: "Z2FDTNDATAQYW2"
        evaluateTargetHealth: false
    - name: "_acme-challenge.asyutdasr43"
      type: TXT
      ttl: 3600
      values:
        - '"vc_jaljp_mqz6dtwcfvh1scdtbi_sybib0ztcmhs2ci"'
    - name: "bbbbb-00005"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "bbbbb-00006"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "bbbbb-00007"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "bryan-teste-public-prd-2"
      type: A
      ttl: 300
      values:
        - "102.46.82.112"
    - name: "bryan-teste-public-prd-3"
      type: A
      ttl: 300
      values:
        - "102.46.82.112"
    - name: "bryan-teste-public-prd"
      type: A
      ttl: 300
      values:
        - "102.46.82.112"
    - name: "bryan-teste-public"
      type: A
      ttl: 300
      values:
        - "102.46.82.112"
    - name: "byan-teste"
      type: A
      ttl: 300
      values:
        - "10.0.1.100"
    - name: "byan-teste23"
      type: A
      ttl: 300
      values:
        - "10.0.1.100"
    - name: "byan-teste2345"
      type: A
      ttl: 300
      values:
        - "10.0.1.200"
    - name: "byan-teste2346"
      type: A
      ttl: 300
      values:
        - "10.0.1.100"
    - name: "_acme-challenge.dasfasdasdw"
      type: TXT
      ttl: 3600
      values:
        - '"vc_jaljp_mqz6dtwcfvh1scdtbi_sybib0ztcmhs2ci"'
    - name: "prd-a-private-multiple-a"
      type: A
      ttl: 3600
      values:
        - "10.0.0.10"
    - name: "prd-a-private-multiple-b"
      type: A
      ttl: 3600
      values:
        - "10.0.0.20"
    - name: "prd-a-private-single"
      type: A
      ttl: 3600
      values:
        - "10.0.0.10"
    - name: "prd-a-public-multiple-a"
      type: A
      ttl: 3600
      values:
        - "202.195.21.69"
    - name: "prd-a-public-multiple-b"
      type: A
      ttl: 3600
      values:
        - "202.151.56.78"
    - name: "prd-a-public-single"
      type: A
      ttl: 3600
      values:
        - "202.195.21.67"
    - name: "prd-cname-public-multiple-a"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "prd-cname-public-multiple-b"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "prd-cname-public-single"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "_acme-challenge.pre-deploy"
      type: TXT
      ttl: 3600
      values:
        - '"vc_jaljp_mqz6dtwcfvh1scdtbi_sybib0ztcmhs2ci"'
    - name: "record-a"
      type: A
      ttl: 3600
      values:
        - "10.0.0.20"
    - name: "record-alias-external"
      type: A
      aliasTarget:
        dnsName: "as9g78as768d7a8sd.cloudfront.net"
        hostedZoneId: "Z2FDTNDATAQYW2"
        evaluateTargetHealth: true
    - name: "record-alias-internal"
      type: A
      aliasTarget:
        dnsName: "record-alias-external.infraprd.hml.dock.tech"
        hostedZoneId: "Z0195231ON0MEFO4W8P4"
        evaluateTargetHealth: true
    - name: "record-cname"
      type: CNAME
      ttl: 300
      values:
        - "example.record.com"
    - name: "record-txt"
      type: TXT
      ttl: 7200
      values:
        - '"BX15BBBBBBBBBBBBBBB"'
    - name: "record-weighted-a"
      type: A
      ttl: 3600
      values:
        - "10.0.0.80"
      setIdentifier: "record-weighted-a-a"
      weight: 204
    - name: "record-weighted-a"
      type: A
      ttl: 3600
      values:
        - "10.0.0.20"
      setIdentifier: "record-weighted-a-b"
      weight: 51
    - name: "record-weighted-cname"
      type: CNAME
      ttl: 7200
      values:
        - "example-a.test.com"
      setIdentifier: "record-weighted-cname-a"
      weight: 255
    - name: "record-weighted-cname"
      type: CNAME
      ttl: 7200
      values:
        - "example-b.test.com"
      setIdentifier: "record-weighted-cname-b"
      weight: 0
    - name: "test-freezing"
      type: CNAME
      ttl: 3600
      values:
        - "dock.tech"
    - name: "test-new-record"
      type: A
      ttl: 300
      values:
        - "192.0.2.100"
    - name: "test-prd-api-1762887916"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1762891698"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1764183698"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1764186767"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1764200637"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1764201483"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1764632050"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1764679445"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api-1764725067"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "test-prd-api"
      type: A
      ttl: 300
      values:
        - "52.85.151.23"
    - name: "teste1"
      type: A
      ttl: 3600
      values:
        - "10.0.0.1"
    - name: "teste2"
      type: A
      ttl: 3600
      values:
        - "10.0.0.2"
    - name: "_acme-challenge.wasdawd124easd"
      type: TXT
      ttl: 3600
      values:
        - '"vc_jaljp_mqz6dtwcfvh1scdtbi_sybib0ztcmhs2ci"'
    - name: "_acme-challenge.wat"
      type: TXT
      ttl: 3600
      values:
        - '"vc_jaljp_mqz6dtwcfvh1scdtbi_sybib0ztcmhs2ci"'
    - name: "zzzz-alias1"
      type: A
      aliasTarget:
        dnsName: "exemplo01.cloudfront.net"
        hostedZoneId: "Z2FDTNDATAQYW2"
        evaluateTargetHealth: false
