---
apiVersion: dock.tech/v1
kind: Zone
metadata:
  name: zone-external.dev.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"environment":"dev","private":false,"delegatedZone":"resource:system-infrastructure-dev/zone-dev.arthurbryan.com","prefix":"external","tags":{}}'
spec:
  name: zone-external.dev.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 309670275661
    accountName: dev-account
  zoneName: external.dev.arthurbryan.com
  delegatedFromZoneId: Z08530593BJKRSAKMDBYE
  delegatedFromAccountName: dev-account
  visibility: public
