---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-smoke-mx.hml.arthurbryan.com
  namespace: system-dns-hml
  annotations:
    dock.tech/scaffolder-parameters: '{"name":"dns-smoke-mx-hml","system":"system:dns-eds437/dns","environment":"hml","zone":"hml.arthurbryan.com","zoneId":"Z091442636MPUK86SZJ1T","recordName":"smoke-mx","type":"MX","originalType":"MX","ttl":3600,"values":["10
      mail.example.com"],"enableWeightedRouting":false}'
spec:
  name: record-smoke-mx.hml.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: hml
  zoneId: Z091442636MPUK86SZJ1T
  zoneName: hml.arthurbryan.com
  recordName: smoke-mx
  type: MX
  aws:
    account: 382598791794
    accountName: hml-account
  ttl: 3600
  values:
  - 10 mail.example.com
