---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: claim-checkout-134856-hml-arthurbryan-com-a
  namespace: system-infrastructure-hml
  title: checkout-134856.hml.arthurbryan.com
  description: "Claimed A record checkout-134856.hml.arthurbryan.com (hml)"
  annotations:
    dock.tech/xr-kind: Record
    dock.tech/xr-name: claim-checkout-134856-hml-arthurbryan-com-a
    dock.tech/zone-name: hml.arthurbryan.com
    dock.tech/zone-id: Z02234832G6QGRGKEEUMU
    dock.tech/record-name: "checkout-134856"
    dock.tech/record-type: A
    dock.tech/record-fqdn: checkout-134856.hml.arthurbryan.com
    dock.tech/domain: cross
    dock.tech/subdomain: cloud
    dock.tech/system: infrastructure
    dock.tech/environment: hml
    dock.tech/aws-account-id: "382598791794"
    dock.tech/aws-account-name: hml-account
    dock.tech/managed-by: scaffolder
    dock.tech/import-existing: "true"
    dock.tech/scaffolder-parameters: '{"environment":"hml","existingRecord":{"name":"checkout-134856.hml.arthurbryan.com","type":"A","ttl":300,"values":["10.7.8.9"]},"zoneId":"Z02234832G6QGRGKEEUMU"}'
    backstage.io/source-location: "url:https://github.com/arthur-bryan/aws-dns-crossplane-poc/blob/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/hml/resources/aws/hml.arthurbryan.com/record-claim-checkout-134856-hml-arthurbryan-com-a.yaml"
  tags:
    - aws
    - dns
    - route53
    - record
    - claimed
    - a
    - hml
  links:
    - title: Remove platform claim (opens GitHub delete UI; AWS record is preserved)
      url: https://github.com/arthur-bryan/aws-dns-crossplane-poc/delete/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/hml/resources/aws/hml.arthurbryan.com/record-claim-checkout-134856-hml-arthurbryan-com-a.yaml
      icon: delete
spec:
  type: aws-dns-record
  owner: group:default/infrastructure
  system: infrastructure
  dependsOn:
    - resource:default/zone-hml.arthurbryan.com
