---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: zone-hml.arthurbryan.com
  namespace: system-infrastructure-hml
  title: "hml.arthurbryan.com · hml"
  description: "Route53 Hosted Zone hml.arthurbryan.com (hml) — delegated from arthurbryan.com"
  annotations:
    dock.tech/xr-kind: Zone
    dock.tech/xr-name: zone-hml.arthurbryan.com
    dock.tech/zone-name: hml.arthurbryan.com
    dock.tech/parent-zone-id: Z03010981ALJFZB4QLU8W
    dock.tech/parent-zone-name: arthurbryan.com
    dock.tech/parent-aws-account-name: prd-account
    dock.tech/domain: cross
    dock.tech/subdomain: cloud
    dock.tech/system: infrastructure
    dock.tech/environment: hml
    dock.tech/aws-account-id: "382598791794"
    dock.tech/aws-account-name: hml-account
    dock.tech/visibility: public
    dock.tech/managed-by: scaffolder
    backstage.io/source-location: "url:https://github.com/arthur-bryan/aws-dns-crossplane-poc/blob/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/hml/resources/aws/hml.arthurbryan.com/zone.yaml"
  tags:
    - aws
    - dns
    - route53
    - zone
    - hml
    - public
  links:
    - title: View in AWS Console
      url: https://console.aws.amazon.com/route53/v2/hostedzones
      icon: cloud
    - title: Delete zone (opens GitHub delete UI)
      url: https://github.com/arthur-bryan/aws-dns-crossplane-poc/delete/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/hml/resources/aws/hml.arthurbryan.com/zone.yaml
      icon: delete
spec:
  type: aws-dns-zone
  owner: group:default/infrastructure
  system: infrastructure
  dependsOn:
    - resource:default/zone-arthurbryan.com
