---
apiVersion: dock.tech/v1
kind: Record
metadata:
  name: record-test.internal.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-dev/zone-internal.arthurbryan.com","recordName":"test","type":"A","ttl":300,"values":["10.0.0.42"],"routingPolicy":"simple"}'
spec:
  name: record-test.internal.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 597230762851
    accountName: dev-account
  zoneId: Z023605847CN76CUAJYF
  zoneName: internal.arthurbryan.com
  recordName: test
  type: A
  ttl: 300
  values:
    - 10.0.0.42
  import:
    existing: true
