---
apiVersion: dock.tech/v1
kind: Zone
metadata:
  name: zone-internal.arthurbryan.com
  namespace: system-infrastructure-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"delegatedZone":"resource:system-infrastructure-dev/zone-arthurbryan.com","prefix":"internal","private":true,"vpcs":["resource:default/vpc-0410f81cfe1bba322"],"deletionProtection":false}'
spec:
  name: zone-internal.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: infrastructure
  environment: dev
  aws:
    account: 597230762851
    accountName: dev-account
  zoneName: internal.arthurbryan.com
  delegatedFromZoneId: Z03010981ALJFZB4QLU8W
  visibility: private
  vpcs:
    - vpcId: vpc-0410f81cfe1bba322
      vpcRegion: us-east-1
