apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: dnszones.aws.dns.crossplane.poc.observe
  labels:
    provider: aws
    service: route53
    mode: observe
spec:
  writeConnectionSecretsToNamespace: crossplane-system
  compositeTypeRef:
    apiVersion: dns.crossplane.poc/v1alpha1
    kind: XDNSZone

  mode: Pipeline

  pipeline:
    - step: observe-zone
      functionRef:
        name: function-patch-and-transform
      input:
        apiVersion: pt.fn.crossplane.io/v1beta1
        kind: Resources
        resources:
          - name: zone
            base:
              apiVersion: route53.aws.upbound.io/v1beta1
              kind: Zone
              spec:
                managementPolicies: ["Observe"]
                deletionPolicy: Orphan
                forProvider:
                  region: us-east-1
            patches:
              - type: FromCompositeFieldPath
                fromFieldPath: metadata.annotations[crossplane.io/external-name]
                toFieldPath: metadata.annotations[crossplane.io/external-name]

              - type: FromCompositeFieldPath
                fromFieldPath: spec.zoneName
                toFieldPath: spec.forProvider.name

              - type: FromCompositeFieldPath
                fromFieldPath: spec.comment
                toFieldPath: spec.forProvider.comment
                policy:
                  fromFieldPath: Optional

              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: spec.providerConfigRef.name
                transforms:
                  - type: string
                    string:
                      type: Format
                      fmt: "aws-%s"

              - type: FromCompositeFieldPath
                fromFieldPath: spec.environment
                toFieldPath: spec.forProvider.tags.Environment

              - type: FromCompositeFieldPath
                fromFieldPath: spec.tags
                toFieldPath: spec.forProvider.tags
                policy:
                  fromFieldPath: Optional

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.id
                toFieldPath: status.zoneId

              - type: ToCompositeFieldPath
                fromFieldPath: status.atProvider.nameServers
                toFieldPath: status.nameServers

            readinessChecks:
              - type: MatchCondition
                matchCondition:
                  type: Ready
                  status: "True"
