providers:
  - name: upbound-provider-aws-route53
    package: xpkg.upbound.io/upbound/provider-aws-route53:v1.7.0
    runtimeConfig:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::PLACEHOLDER:role/crossplane-dns"

  - name: upbound-provider-aws-cloudformation
    package: xpkg.upbound.io/upbound/provider-aws-cloudformation:v1.7.0
    runtimeConfig:
      annotations:
        eks.amazonaws.com/role-arn: "arn:aws:iam::PLACEHOLDER:role/crossplane-dns"
