---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: record-wat.arthurbryan.com
  namespace: system-infrastructure-prd
  title: wat.arthurbryan.com
  description: "DNS A record wat.arthurbryan.com (prd)"
  annotations:
    dock.tech/xr-kind: Record
    dock.tech/xr-name: record-wat.arthurbryan.com
    dock.tech/zone-name: arthurbryan.com
    dock.tech/zone-id: Z03010981ALJFZB4QLU8W
    dock.tech/record-name: wat
    dock.tech/record-type: A
    dock.tech/record-fqdn: wat.arthurbryan.com
    dock.tech/domain: cross
    dock.tech/subdomain: cloud
    dock.tech/system: infrastructure
    dock.tech/environment: prd
    dock.tech/managed-by: scaffolder

    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"wat","type":"A","ttl":3600,"values":["10.0.0.10"],"evaluateTargetHealth":false,"routingPolicy":"simple"}'
    backstage.io/edit-url: /create/templates/default/aws-dns-record-edit?formData=%7B%22zone%22%3A%22resource%3Asystem-infrastructure-prd%2Fzone-arthurbryan.com%22%2C%22recordName%22%3A%22wat%22%2C%22type%22%3A%22A%22%2C%22ttl%22%3A3600%2C%22values%22%3A%5B%2210.0.0.10%22%5D%2C%22evaluateTargetHealth%22%3Afalse%2C%22routingPolicy%22%3A%22simple%22%7D
    backstage.io/source-location: "url:https://github.com/arthur-bryan/aws-dns-crossplane-poc/blob/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/prd/resources/aws/arthurbryan.com/record-wat.yaml"
  tags:
    - aws
    - dns
    - route53
    - record
    - a
    - prd
spec:
  type: aws-dns-record
  owner: group:default/infrastructure
  system: infrastructure
  dependsOn:
    - resource:default/zone-arthurbryan.com
