---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: record-e2e-failover-type-swap-085707-rotate.arthurbryan.com
  namespace: system-infrastructure-prd
  title: e2e-failover-type-swap-085707.arthurbryan.com
  description: "DNS A record e2e-failover-type-swap-085707.arthurbryan.com (prd)"
  annotations:
    dock.tech/xr-kind: Record
    dock.tech/xr-name: record-e2e-failover-type-swap-085707-rotate.arthurbryan.com
    dock.tech/zone-name: arthurbryan.com
    dock.tech/zone-id: Z03010981ALJFZB4QLU8W
    dock.tech/record-name: "e2e-failover-type-swap-085707"
    dock.tech/record-type: A
    dock.tech/record-fqdn: e2e-failover-type-swap-085707.arthurbryan.com
    dock.tech/domain: cross
    dock.tech/subdomain: cloud
    dock.tech/system: infrastructure
    dock.tech/environment: prd
    dock.tech/managed-by: scaffolder
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-failover-type-swap-085707","type":"A","routingPolicy":"failover","setIdentifier":"rotate","failoverType":"PRIMARY","healthCheckId":"fd13e0d2-2f29-40a1-a40d-59e0b54fac48","ttl":300,"values":["10.0.32.10"]}'
    backstage.io/edit-url: /create/templates/default/aws-dns-record-edit?formData=%7B%22zone%22%3A%22resource%3Asystem-infrastructure-prd%2Fzone-arthurbryan.com%22%2C%22recordName%22%3A%22e2e-failover-type-swap-085707%22%2C%22type%22%3A%22A%22%2C%22routingPolicy%22%3A%22failover%22%2C%22setIdentifier%22%3A%22rotate%22%2C%22failoverType%22%3A%22PRIMARY%22%2C%22healthCheckId%22%3A%22fd13e0d2-2f29-40a1-a40d-59e0b54fac48%22%2C%22ttl%22%3A300%2C%22values%22%3A%5B%2210.0.32.10%22%5D%7D
    backstage.io/source-location: "url:https://github.com/arthur-bryan/aws-dns-crossplane-poc/blob/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/prd/resources/aws/arthurbryan.com/record-e2e-failover-type-swap-085707-rotate.yaml"
  tags:
    - aws
    - dns
    - route53
    - record
    - a
    - prd
  links:
    - title: View in AWS Console
      url: https://console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z03010981ALJFZB4QLU8W
      icon: cloud
    - title: Delete record (opens GitHub delete UI)
      url: https://github.com/arthur-bryan/aws-dns-crossplane-poc/delete/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/prd/resources/aws/arthurbryan.com/record-e2e-failover-type-swap-085707-rotate.yaml
      icon: delete
spec:
  type: aws-dns-record
  owner: group:default/infrastructure
  system: infrastructure
  dependsOn:
    - resource:default/zone-arthurbryan.com
