---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: record-api-api-primary.arthurbryan.com
  namespace: system-infrastructure-prd
  title: api.arthurbryan.com (api-primary)
  description: "DNS A record api.arthurbryan.com (prd) — imported"
  annotations:
    dock.tech/xr-kind: Record
    dock.tech/xr-name: record-api-api-primary.arthurbryan.com
    dock.tech/zone-name: arthurbryan.com
    dock.tech/zone-id: Z03010981ALJFZB4QLU8W
    dock.tech/record-name: api
    dock.tech/record-type: A
    dock.tech/record-fqdn: api.arthurbryan.com
    dock.tech/domain: cross
    dock.tech/subdomain: cloud
    dock.tech/system: infrastructure
    dock.tech/environment: prd
    dock.tech/managed-by: batch-import
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"api","type":"A","ttl":300,"values":["10.0.1.11"],"routingPolicy":"weighted","setIdentifier":"api-primary","weight":70}'
    backstage.io/edit-url: "http://localhost:3000/create/templates/default/aws-dns-record-edit?formData=%7B%22zone%22%3A%22resource%3Asystem-infrastructure-prd%2Fzone-arthurbryan.com%22%2C%22recordName%22%3A%22api%22%2C%22type%22%3A%22A%22%2C%22setIdentifier%22%3A%22api-primary%22%7D"

    backstage.io/source-location: "url:https://github.com/arthur-bryan/aws-dns-crossplane-poc/blob/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/prd/resources/aws/arthurbryan.com/record-api-primary.yaml"
  tags:
    - aws
    - dns
    - route53
    - record
    - a
    - imported
    - prd
  links:
    - title: View in AWS Console
      url: https://console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z03010981ALJFZB4QLU8W
      icon: cloud
    - title: Delete record (opens GitHub delete UI)
      url: https://github.com/arthur-bryan/aws-dns-crossplane-poc/delete/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/prd/resources/aws/arthurbryan.com/record-api-primary.yaml
      icon: delete
spec:
  type: aws-dns-record
  owner: group:default/infrastructure
  system: infrastructure
  dependsOn:
    - resource:default/zone-arthurbryan.com
