---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: record-e2e-conc-siblings-024742-primary.arthurbryan.com
  namespace: system-infrastructure-prd
  title: e2e-conc-siblings-024742.arthurbryan.com
  description: "DNS A record e2e-conc-siblings-024742.arthurbryan.com (prd)"
  annotations:
    dock.tech/xr-kind: Record
    dock.tech/xr-name: record-e2e-conc-siblings-024742-primary.arthurbryan.com
    dock.tech/zone-name: arthurbryan.com
    dock.tech/zone-id: Z03010981ALJFZB4QLU8W
    dock.tech/record-name: "e2e-conc-siblings-024742"
    dock.tech/record-type: A
    dock.tech/record-fqdn: e2e-conc-siblings-024742.arthurbryan.com
    dock.tech/domain: cross
    dock.tech/subdomain: cloud
    dock.tech/system: infrastructure
    dock.tech/environment: prd
    dock.tech/managed-by: scaffolder
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-prd/zone-arthurbryan.com","recordName":"e2e-conc-siblings-024742","type":"A","ttl":600,"values":["10.0.41.11"],"routingPolicy":"weighted","setIdentifier":"primary","weight":70}'
    backstage.io/edit-url: http://localhost:3000/create/templates/default/aws-dns-record-edit?formData=%7B%22zone%22%3A%22resource%3Asystem-infrastructure-prd%2Fzone-arthurbryan.com%22%2C%22recordName%22%3A%22e2e-conc-siblings-024742%22%2C%22type%22%3A%22A%22%7D
    backstage.io/source-location: "url:https://github.com/arthur-bryan/aws-dns-crossplane-poc/blob/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/prd/resources/aws/arthurbryan.com/record-e2e-conc-siblings-024742-primary.yaml"
  tags:
    - aws
    - dns
    - route53
    - record
    - a
    - prd
  links:
    - title: View in AWS Console
      url: https://console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z03010981ALJFZB4QLU8W
      icon: cloud
    - title: Delete record (opens GitHub delete UI)
      url: https://github.com/arthur-bryan/aws-dns-crossplane-poc/delete/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/prd/resources/aws/arthurbryan.com/record-e2e-conc-siblings-024742-primary.yaml
      icon: delete
spec:
  type: aws-dns-record
  owner: group:default/infrastructure
  system: infrastructure
  dependsOn:
    - resource:default/zone-arthurbryan.com
