---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-claim-weighted.dev.arthurbryan.com-primary
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-claim-weighted-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"claim-weighted","type":"A","originalType":"A","entityRef":"resource:dns-eds437/dns-claim-weighted-dev","enableWeightedRouting":true,"setIdentifier":"primary","weight":100,"ttl":300,"values":["10.0.2.200"]}'
spec:
  name: record-claim-weighted.dev.arthurbryan.com-primary
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: claim-weighted
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 300
  values:
  - 10.0.2.200
  setIdentifier: primary
  weight: 100
  import:
    existing: true
