---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-matrixalias2.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"matrixalias2","entityRef":"resource:dns-eds437/matrixalias2","recordName":"matrixalias2","type":"ALIAS","serviceType":"ALB","region":"sa-east-1","dnsName":"my-alb-999999.sa-east-1.elb.amazonaws.com","originalType":"ALIAS"}'
spec:
  name: record-matrixalias2.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: matrixalias2
  recordType: ALIAS
  aws:
    account: 309670275661
    accountName: dev-account
  aliasTarget:
    serviceType: ALB
    dnsName: my-alb-999999.sa-east-1.elb.amazonaws.com
    region: sa-east-1
