---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-editclaimcname.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-editclaimcname-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"editclaimcname","type":"CNAME","originalType":"CNAME","entityRef":"resource:dns-eds437/dns-editclaimcname-dev","ttl":300,"values":["target1.example.com"]}'
spec:
  name: record-editclaimcname.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: editclaimcname
  recordType: CNAME
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 300
  values:
  - target1.example.com
  import:
    existing: true
