---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-matrixaaaa2.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"matrixaaaa2","type":"AAAA","values":["2001:db8::1"],"recordName":"matrixaaaa2","entityRef":"resource:dns-eds437/matrixaaaa2"}'
spec:
  name: record-matrixaaaa2.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: matrixaaaa2
  recordType: AAAA
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - 2001:db8::1
