---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-smoke-mx.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-smoke-mx-dev","name":"dns-smoke-mx-dev","system":"system:dns-eds437/dns","environment":"dev","zone":"dev.arthurbryan.com","zoneId":"Z0945364EYNE5KZW0WIF","recordName":"smoke-mx","type":"MX","enableWeightedRouting":false,"values":["20
      mail2.example.com"],"ttl":3600}'
spec:
  name: record-smoke-mx.dev.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: smoke-mx
  type: MX
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - 20 mail2.example.com
