---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-s3websitetest.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-s3websitetest-dev","type":"ALIAS","enableWeightedRouting":false,"serviceType":"S3Website","region":"us-east-1","dnsName":"my-test-bucket.s3-website-us-east-1.amazonaws.com","evaluateTargetHealth":false,"values":[null],"recordName":"s3websitetest","entityRef":"resource:dns-eds437/dns-s3websitetest-dev"}'
spec:
  name: record-s3websitetest.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: s3websitetest
  recordType: ALIAS
  aws:
    account: 309670275661
    accountName: dev-account
  aliasTarget:
    serviceType: S3Website
    dnsName: my-test-bucket.s3-website-us-east-1.amazonaws.com
    evaluateTargetHealth: false
    region: us-east-1
