---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-batch-a2.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"batch-a2","type":"A","values":["10.60.0.2"],"recordName":"batch-a2","entityRef":"resource:dns-eds437/batch-a2"}'
spec:
  name: record-batch-a2.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: batch-a2
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - 10.60.0.2
