---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-multi-txt.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"multi-txt","type":"TXT","values":["v=spf1
      include:example.com ~all"],"recordName":"multi-txt","entityRef":"resource:dns-eds437/multi-txt"}'
spec:
  name: record-multi-txt.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: multi-txt
  recordType: TXT
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - v=spf1 include:example.com ~all
