---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-cdn.dev.arthurbryan.com
  namespace: system-dns-dev
spec:
  name: record-cdn.dev.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: cdn
  type: ALIAS
  aws:
    account: 309670275661
    accountName: dev-account
  aliasTarget:
    serviceType: Custom
    dnsName: api.dev.arthurbryan.com
    hostedZoneId: Z0945364EYNE5KZW0WIF
    evaluateTargetHealth: false
