---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-badiptest.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-badiptest-dev","type":"A","enableWeightedRouting":false,"values":["999.999.999.999"],"recordName":"badiptest","entityRef":"resource:dns-eds437/dns-badiptest-dev"}'
spec:
  name: record-badiptest.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: badiptest
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - 999.999.999.999
