---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-editclaimweighted.dev.arthurbryan.com-primary
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"entityRef":"resource:dns-eds437/dns-editclaimweighted-dev-primary","name":"dns-editclaimweighted-dev-primary","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"editclaimweighted","type":"A","values":["10.0.6.2"],"enableWeightedRouting":true,"setIdentifier":"primary","weight":77,"originalType":"A"}'
spec:
  name: record-editclaimweighted.dev.arthurbryan.com-primary
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: editclaimweighted
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 600
  values:
  - 10.0.6.2
  setIdentifier: primary
  weight: 77
