---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-evweightedtest.dev.arthurbryan.com-primary
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-evweightedtest-dev-primary","type":"A","enableWeightedRouting":true,"values":["10.95.95.1"],"setIdentifier":"primary","weight":50,"recordName":"evweightedtest","entityRef":"resource:dns-eds437/dns-evweightedtest-dev-primary"}'
spec:
  name: record-evweightedtest.dev.arthurbryan.com-primary
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: evweightedtest
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 600
  values:
  - 10.95.95.1
  setIdentifier: primary
  weight: 128
