---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-scn-weighted2.dev.arthurbryan.com-west
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-scn-weighted2-dev-west","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"scn-weighted2","type":"A","originalType":"A","entityRef":"resource:dns-eds437/dns-scn-weighted2-dev-west","enableWeightedRouting":true,"setIdentifier":"west","weight":50,"ttl":300,"values":["10.0.3.20"]}'
spec:
  name: record-scn-weighted2.dev.arthurbryan.com-west
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: scn-weighted2
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 300
  values:
  - 10.0.3.20
  setIdentifier: west
  weight: 50
  import:
    existing: true
