---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-scn-alias-cf.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-scn-alias-cf-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"scn-alias-cf","type":"ALIAS","originalType":"ALIAS","entityRef":"resource:dns-eds437/dns-scn-alias-cf-dev","serviceType":"CloudFront","dnsName":"d111111abcdef8.cloudfront.net","evaluateTargetHealth":false}'
spec:
  name: record-scn-alias-cf.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: scn-alias-cf
  recordType: ALIAS
  aws:
    account: 309670275661
    accountName: dev-account
  aliasTarget:
    serviceType: Custom
    dnsName: d111111abcdef8.cloudfront.net
    hostedZoneId: Z2FDTNDATAQYW2
    evaluateTargetHealth: false
  import:
    existing: true
