---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-atoaliasswap.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-atoaliasswap-dev","type":"ALIAS","enableWeightedRouting":false,"values":["10.20.30.40"],"recordName":"atoaliasswap","entityRef":"resource:dns-eds437/dns-atoaliasswap-dev","evaluateTargetHealth":false,"serviceType":"CloudFront","region":"global","dnsName":"d222222xyzabc9.cloudfront.net","originalType":"ALIAS"}'
spec:
  name: record-atoaliasswap.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: atoaliasswap
  recordType: ALIAS
  aws:
    account: 309670275661
    accountName: dev-account
  aliasTarget:
    serviceType: CloudFront
    dnsName: d222222xyzabc9.cloudfront.net
    evaluateTargetHealth: false
