---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-matrixa2.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"matrixa2","type":"A","values":["10.20.1.2","10.20.1.3"],"recordName":"matrixa2","entityRef":"resource:dns-eds437/matrixa2"}'
spec:
  name: record-matrixa2.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: matrixa2
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - 10.20.1.2
  - 10.20.1.3
