---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-evweight.dev.arthurbryan.com-primary
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-evweight-dev-primary","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"evweight","type":"A","originalType":"A","entityRef":"resource:dns-eds437/dns-evweight-dev-primary","enableWeightedRouting":true,"setIdentifier":"primary","weight":50,"ttl":600,"values":["10.90.90.1"]}'
spec:
  name: record-evweight.dev.arthurbryan.com-primary
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: evweight
  recordType: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 600
  values:
  - 10.90.90.1
  setIdentifier: primary
  weight: 128
  import:
    existing: true
