---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-mix5-cname.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"mix5-cname","type":"CNAME","values":["api5.example.com"],"recordName":"mix5-cname","entityRef":"resource:dns-eds437/mix5-cname"}'
spec:
  name: record-mix5-cname.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: mix5-cname
  recordType: CNAME
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - api5.example.com
