---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-wtestaaaa.dev.arthurbryan.com-primary6
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-wtestaaaa-dev","type":"AAAA","enableWeightedRouting":true,"values":["2001:db8::a1"],"recordName":"wtestaaaa","entityRef":"resource:dns-eds437/dns-wtestaaaa-dev","weight":40,"setIdentifier":"primary6","originalType":"AAAA"}'
spec:
  name: record-wtestaaaa.dev.arthurbryan.com-primary6
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: wtestaaaa
  recordType: AAAA
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 600
  values:
  - 2001:db8::a1
  setIdentifier: primary6
  weight: 40
