---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-templatetest.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-templatetest-dev","system":"system:dns-eds437/dns","environment":"dev","zone":"dev.arthurbryan.com","zoneId":"Z0945364EYNE5KZW0WIF","recordName":"templatetest","type":"A","originalType":"A","values":["10.99.0.1"],"enableWeightedRouting":false}'
spec:
  name: record-templatetest.dev.arthurbryan.com
  domain: cross
  subdomain: cloud
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: templatetest
  type: A
  aws:
    account: 309670275661
    accountName: dev-account
  ttl: 3600
  values:
  - 10.99.0.1
