---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-evelasticbeanstalk.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"kind":"Record","name":"dns-evelasticbeanstalk-dev","type":"ALIAS","enableWeightedRouting":false,"serviceType":"ElasticBeanstalk","region":"us-east-1","dnsName":"ev-eb-env.us-east-1.elasticbeanstalk.com","evaluateTargetHealth":false,"values":[null],"recordName":"evelasticbeanstalk","entityRef":"resource:dns-eds437/dns-evelasticbeanstalk-dev"}'
spec:
  name: record-evelasticbeanstalk.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: evelasticbeanstalk
  recordType: ALIAS
  aws:
    account: 309670275661
    accountName: dev-account
  aliasTarget:
    serviceType: ElasticBeanstalk
    dnsName: ev-eb-env.us-east-1.elasticbeanstalk.com
    evaluateTargetHealth: false
    region: us-east-1
