---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-e2ealias021732.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-e2ealias021732-dev","type":"ALIAS","serviceType":"CloudFront","dnsName":"d111111abcdef8.cloudfront.net","evaluateTargetHealth":false,"enableWeightedRouting":false,"recordName":"e2ealias021732","entityRef":"resource:/dns-e2ealias021732-dev"}'
spec:
  name: record-e2ealias021732.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: e2ealias021732
  recordType: ALIAS
  aliasTarget:
    serviceType: CloudFront
    dnsName: d111111abcdef8.cloudfront.net
    evaluateTargetHealth: false
