---
apiVersion: dock.tech/v1
kind: DNSRecord
metadata:
  name: record-evsamezone.dev.arthurbryan.com
  namespace: system-dns-dev
  annotations:
    dock.tech/generated-by: catalog-to-xr
    dock.tech/scaffolder-parameters: '{"name":"dns-evsamezone-dev","system":"system:dns-eds437/dns","environment":"dev","zone":{"id":"Z0945364EYNE5KZW0WIF","name":"dev.arthurbryan.com","accountName":"dev-account","environment":"dev"},"recordName":"evsamezone","type":"ALIAS","originalType":"ALIAS","entityRef":"resource:dns-eds437/dns-evsamezone-dev","serviceType":"SameZoneRecord","dnsName":"api.dev.arthurbryan.com","evaluateTargetHealth":false}'
spec:
  name: record-evsamezone.dev.arthurbryan.com
  domain: cross
  system: dns
  environment: dev
  zoneId: Z0945364EYNE5KZW0WIF
  zoneName: dev.arthurbryan.com
  recordName: evsamezone
  recordType: ALIAS
  aws:
    account: 309670275661
    accountName: dev-account
  aliasTarget:
    serviceType: SameZoneRecord
    dnsName: api.dev.arthurbryan.com
    evaluateTargetHealth: false
  import:
    existing: true
