---
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: record-bryan.arthurbryan.com
  namespace: system-infrastructure-dev
  title: bryan.arthurbryan.com
  description: "DNS A record bryan.arthurbryan.com (dev)"
  annotations:
    dock.tech/xr-kind: Record
    dock.tech/xr-name: record-bryan.arthurbryan.com
    dock.tech/zone-name: arthurbryan.com
    dock.tech/zone-id: Z03010981ALJFZB4QLU8W
    dock.tech/record-name: bryan
    dock.tech/record-type: A
    dock.tech/record-fqdn: bryan.arthurbryan.com
    dock.tech/domain: cross
    dock.tech/subdomain: cloud
    dock.tech/system: infrastructure
    dock.tech/environment: dev
    dock.tech/managed-by: scaffolder
    dock.tech/scaffolder-parameters: '{"zone":"resource:system-infrastructure-dev/zone-arthurbryan.com","recordName":"bryan","type":"A","ttl":3600,"values":["192.168.0.10"],"routingPolicy":"simple"}'
    backstage.io/edit-url: http://localhost:3000/create/templates/default/aws-dns-record-edit?formData=%7B%22zone%22%3A%22resource%3Asystem-infrastructure-dev%2Fzone-arthurbryan.com%22%2C%22recordName%22%3A%22bryan%22%2C%22type%22%3A%22A%22%7D
    backstage.io/source-location: "url:https://github.com/arthur-bryan/aws-dns-crossplane-poc/blob/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/dev/resources/aws/arthurbryan.com/record-bryan.yaml"
  tags:
    - aws
    - dns
    - route53
    - record
    - a
    - dev
  links:
    - title: View in AWS Console
      url: https://console.aws.amazon.com/route53/v2/hostedzones#ListRecordSets/Z03010981ALJFZB4QLU8W
      icon: cloud
    - title: Delete record (opens GitHub delete UI)
      url: https://github.com/arthur-bryan/aws-dns-crossplane-poc/delete/feature/ape-platform-alignment/entities/environments/cross/cloud/infrastructure/dev/resources/aws/arthurbryan.com/record-bryan.yaml
      icon: delete
spec:
  type: aws-dns-record
  owner: group:default/infrastructure
  system: infrastructure
  dependsOn:
    - resource:default/zone-arthurbryan.com
