apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-cloudformation
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-cloudformation:v1.18.0
---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-aws-route53
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: xpkg.upbound.io/upbound/provider-aws-route53:v1.18.0
