---
apiVersion: v1
kind: Namespace
metadata:
  name: system-dns-dev
  labels:
    ape.dock.tech/domain: cross
    ape.dock.tech/subdomain: cloud
    ape.dock.tech/system: dns
    ape.dock.tech/environment: dev
