
app:
  title: APE Backstage
  baseUrl: http://localhost:3000
  listen:
    host: 0.0.0.0
    port: 3000

backend:
  baseUrl: http://localhost:7007
  listen:
    host: 0.0.0.0
    port: 7007

organization:
  name: APE Platform

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  processingInterval: { seconds: 30 }
  rules:
    - allow: [Component, System, API, Resource, Location, Template, Domain, Group, User]
  locations:
    - type: file
      target: ../../../../../entities/catalog-info.yaml
      rules:
        - allow: [Domain, System, Resource, Group]

    - type: file
      target: ../../../../../../backstage-templates/templates/resources/aws/catalog-info.yaml
      rules:
        - allow: [Location, Template]

    - type: file
      target: ../../../../../entities/catalog/**/*.yaml
      rules:
        - allow: [Resource]

scaffolder:
  defaultAuthor:
    name: APE Scaffolder
    email: scaffolder@ape.local
  defaultCommitMessage: "chore(dns): scaffolder-generated change"

dns:
  accounts:
    dev:
      accountId: ${DNS_ACCOUNT_ID_DEV}
      accountName: ${DNS_ACCOUNT_NAME_DEV}
      roleArn: ${DNS_ROLE_ARN_DEV}
    hml:
      accountId: ${DNS_ACCOUNT_ID_HML}
      accountName: ${DNS_ACCOUNT_NAME_HML}
      roleArn: ${DNS_ROLE_ARN_HML}
    prd:
      accountId: ${DNS_ACCOUNT_ID_PRD}
      accountName: ${DNS_ACCOUNT_NAME_PRD}
      roleArn: ${DNS_ROLE_ARN_PRD}

auth:
  providers:
    guest: {}
