
app:
  title: APE Backstage
  baseUrl: http://localhost:3000
  listen:
    host: 0.0.0.0
    port: 3000

backend:
  baseUrl: http://localhost:7007
  listen:
    host: 0.0.0.0
    port: 7007

organization:
  name: APE Platform

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  processingInterval: { seconds: 30 }
  rules:
    - allow: [Component, System, API, Resource, Location, Template, Domain, Group, User]
  locations:
    - type: file
      target: ../../../../../entities/catalog-info.yaml
      rules:
        - allow: [Domain, System, Resource, Group]

    - type: file
      target: ../../../../backstage-templates/catalog-info.yaml
      rules:
        - allow: [Location, Template]

    - type: file
      target: ../../../../../entities/catalog/**/*.yaml
      rules:
        - allow: [Resource]

scaffolder:
  defaultAuthor:
    name: APE Scaffolder
    email: scaffolder@ape.local
  defaultCommitMessage: "chore(dns): scaffolder-generated change"

auth:
  providers:
    guest: {}
